services:
  app:
    build: .
    depends_on:
      - redis
      - grafana
    container_name: g1_python
    volumes:
      - .:/app
  redis:
    container_name: g1_redis
    image: redis:7.2.2-alpine
    ports:
      - 6379:6379
  grafana:
    container_name: g1_grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000